services:
  - type: web
    name: gcpa-calculator
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: GCPA Calculator
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://gcpa-calculator.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: debug